### ISSUE TITLE
Crash when adding controls to the Toolbox

### ISSUE THREAD

**Issue by JasonLandbridge** [dotnetprojects/WpfExtendedToolkit#10]
Hey there, 

When I add this version to the Toolbox in WPF through choose items and then browsing to the dll in .NET Core 3.0, the window freezes and eventually crashes. 

Can you confirm this version is still working?

I am on 4.5.71 and .NET Core 3.0 preview 8

**Comment by jogibear9988** [comment]
I‘ve not tried to add it to the Toolbox.

But I can confirm that the dll works, look at the sample app in the git repo.

Please give some more infos about what you do exactly, maybe I could reproduce.

**Comment by JasonLandbridge** [comment]
Thanks for the quick response! 

I was doing this:
[https://stackoverflow.com/a/11115424](https://stackoverflow.com/a/11115424)

Then when I have selected the assemblies in the nuget package location Visual studio 2019 v16.2.0  freezes and crashes

**Comment by jogibear9988** [comment]
With NetFramework WPF App it works on my system... NetCore I will test now...

**Comment by jogibear9988** [comment]
With NetCore it also does not work... I've no Idea why.
Have you Tested othe NetCore WPF Dll's? Maybe it's a general MS Bug? Or does it only not work with my dll?

**Comment by JasonLandbridge** [comment]
I found out that in a new project based on .Net Core 3.0 I could not add any controls. I tried another similar package ([https://github.com/miqm/wpftoolkit](https://github.com/miqm/wpftoolkit)) and then from SyncFusion but none worked. 

Then I wound the following which might make this a VS2019 issue:
[https://developercommunity.visualstudio.com/content/problem/482527/vs2019rc-custom-controls-are-not-loaded-to-the-too.html](https://developercommunity.visualstudio.com/content/problem/482527/vs2019rc-custom-controls-are-not-loaded-to-the-too.html)

**Comment by jogibear9988** [comment]
I think you should create a new issue. The one you mention is about WPF
But with Wpf it works

**Comment by jogibear9988** [comment]
maybe create it here
https://github.com/dotnet/wpf/issues

**Comment by vatsan-madhavan** [comment]
FYI - https://github.com/dotnet/wpf/issues/1852#issuecomment-533272708

**Comment by JasonLandbridge** [comment]
> 
> 
> FYI - [dotnet/wpf#1852 (comment)](https://github.com/dotnet/wpf/issues/1852#issuecomment-533272708)

Thank you, I will wait for the full .net core 3.0 release this Monday then!

**Comment by jogibear9988** [comment]
@vatsan-madhavan still crashing adding this to newest visual studio16.3.0

**Comment by vatsan-madhavan** [comment]
@diverdan92, This doesn't repro for me in 16.4 previews, but it seems to be crashing in 16.3.0. Can you help redirect to the right folks in VS?

**Comment by jogibear9988** [comment]
I've now tried also in 16.4, also crashing

**Comment by jogibear9988** [comment]
@vatsan-madhavan are you sure you adding the netcore3 dll to the toolbox and not the wpf one?

**Comment by jogibear9988** [comment]
because when I use the wpf dll it works, the netcore one not

**Comment by vatsan-madhavan** [comment]
> @vatsan-madhavan are you sure you adding the netcore3 dll to the toolbox and not the wpf one?
> because when I use the wpf dll it works (even in a netcore app), the netcore one not

![WQbWgrZPsw](https://user-images.githubusercontent.com/20246435/65466406-952cd900-de13-11e9-8a65-b4c3fb0878ed.gif)

**Comment by jogibear9988** [comment]
I close this here as it is a VS bug
