### ISSUE TITLE
How can I use the namespace Xceed.Wpf.Toolkit.Themes in your package in an XML namespace?

### ISSUE THREAD

**Issue by silviubogan** [dotnetprojects/WpfExtendedToolkit#11]
I am coming from the Xceed Extended WPF Toolkit to this project. I use both AvalonDock and other controls found in Xceed Extended WPF Toolkit 3.5, the latest version on NuGet. I uninstalled it and installed Dirkster99's AvalonDock and your package. In a theme resource dictionary file I use this namespace:

```xaml
xmlns:xtkThemes="clr-namespace:Xceed.Wpf.Toolkit.Themes;assembly=Xceed.Wpf.Toolkit"
```

I have it used from a copied default Style for xtk:SplitButton in which there are these:

```xaml
<Setter Property="Background" Value="{DynamicResource {ComponentResourceKey ResourceId=ButtonNormalBackgroundKey, TypeInTargetAssembly={x:Type xtkThemes:ResourceKeys}}}"/>
<Setter Property="BorderBrush" Value="{DynamicResource {ComponentResourceKey ResourceId=ButtonNormalOuterBorderKey, TypeInTargetAssembly={x:Type xtkThemes:ResourceKeys}}}"/>
```

In another place:

```xaml
<Setter Property="BorderBrush" Value="{DynamicResource {ComponentResourceKey ResourceId=ControlNormalBorderKey, TypeInTargetAssembly={x:Type xtkThemes:ResourceKeys}}}"/>
```

In another place:

```xaml
<Setter Property="BorderBrush" Value="{DynamicResource {ComponentResourceKey ResourceId=ControlMouseOverBorderKey, TypeInTargetAssembly={x:Type xtkThemes:ResourceKeys}}}"/>
```

In another place:

```xaml
<Setter Property="BorderBrush" Value="{DynamicResource {ComponentResourceKey ResourceId=ControlSelectedBorderKey, TypeInTargetAssembly={x:Type xtkThemes:ResourceKeys}}}"/>
```

This namespace is not found anymore. What can I do about it?

Thank you.

**Comment by jogibear9988** [comment]
Namespace should be the same, but Assembly name is: DotNetProjects.Wpf.Extended.Toolkit
But you need to update to the last Version I pushed seconds ago

**Comment by silviubogan** [comment]
In the meantime I removed the references to that assembly. If it helps, I saw that there isn't any new version published these days in NuGet. If you need this, I can test again if those references work.

Thank you.
