### ISSUE TITLE
Still need old Xceed.Wpf.Toolkit.dll for getting solution running

### ISSUE THREAD

**Issue by pimaSMS** [dotnetprojects/WpfExtendedToolkit#18]
I moved from the commercial Xceed package to dotnetprojects WpfExtendedToolkit, but somehow my solution won't run unless I put the old Xceed 3.6 Xceed.Wpf.Toolkit.dll in my bin directory.

In my project, I use the dotnetproject toolkit this way:

`xmlns:extToolkit="clr-namespace:Xceed.Wpf.Toolkit;assembly=DotNetProjects.Wpf.Extended.Toolkit"`

The normal schemas way won't work too:

`xmlns:extToolkit="http://schemas.xceed.com/wpf/xaml/toolkit"`

In the app.config I specify

`  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="DotNetProjects.Extended.Wpf.Toolkit" publicKeyToken="3e4669d2f30244f4" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.6.82.0" newVersion="4.6.82.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`

but when I start the program I get the error message

FileNotFoundException: Could not load file or assembly 'Xceed.Wpf.Toolkit, PublicKeyToken=3e4669d2f30244f4'. The system cannot find the file specified.

Do you know what goes wrong or did I forget something? I already deleted the .vs folder.

Kind regards,
Markus

**Comment by jogibear9988** [comment]
maybe you have other dll‘s referencing it? maybe it‘s still in csproj or packages.json?

**Comment by jogibear9988** [comment]
maybe it‘s still referenced in some xaml files?

**Comment by pimaSMS** [comment]
Checked it, no xceed references, just in the one xaml.

BUT a framework from my company uses Xceed too, that was the solution. Thanks for the hint @jogibear9988
