### ISSUE TITLE
Update to 3.7?

### ISSUE THREAD

**Issue by miqm** [dotnetprojects/WpfExtendedToolkit#20]
Hi folks,

Have it been considered to upgrade code to 3.7 - the last version with MS-PL license?

and BTW - license.md file could be added to the repository folder.

**Comment by jogibear9988** [comment]
In this issue someone wrote that in 3.7 was the licence change...
https://github.com/xceedsoftware/wpftoolkit/issues/1557

**Comment by miqm** [comment]
@jogibear9988 https://github.com/xceedsoftware/wpftoolkit/blob/3.7.0/license.md - still MS-PL

Plus, in the current readme (Message from Xceed), they (Xceed) are stating that they will republish 3.8 with MS-PL by the end of the year.

**Comment by jogibear9988** [comment]
yes, I've read this.
could you please ask them if this is really like this. I don't want to upgrade and then they say it's illegal

**Comment by miqm** [comment]
Ok, you're right. did some digging in git history - they updated the license on the same day, but instead moving the tag - they just wrote a note in readme.
https://github.com/xceedsoftware/wpftoolkit/tree/1f11573232d6b6f7cff7a0399da9b5f1dcf77780

What a mess.

Anyway, still it's worth adding license.md to this repository, and let's wait for their official commit with 3.8 as MS-PL.

Also, since this repository is more flexible, I'll archive my fork and re-point it to this one.

**Comment by jogibear9988** [comment]
If you'd like to help here, i also could add you as member to the org
