### ISSUE TITLE
Targeting .NET 5/6

### ISSUE THREAD

**Issue by mstefarov** [dotnetprojects/WpfExtendedToolkit#29]
Any plans to support .NET 5 or the upcoming .NET 6?

**Comment by jogibear9988** [comment]
we target netcoreapp3 so net5/6 should work.
but you could create a pull req and add it as target. but i think appveyor also need changes to support it

**Comment by mstefarov** [comment]
Hmm you're right. I was assuming that some changes would be needed for .NET 5/6 support, but I just tried the existing package in .NET 5/6 projects and everything worked well out-of-the-box. Excellent!
