### ISSUE TITLE
Compatibility with Xceed lib, namespace not working

### ISSUE THREAD

**Issue by MichaelTietz** [dotnetprojects/WpfExtendedToolkit#31]
I tried to switch from Xceed.Wpf.Toolkit to this one but have problems on altering the namespace in XAML.
VS2022, NET6, Xceed Wpf Toolkit 4.2, only using the ColorPicker.

old namespace: 
`"clr-namespace:Xceed.Wpf.Toolkit;assembly=Xceed.Wpf.Toolkit"`

tried this and also mixed versions of the old and new namespaces: 
`"clr-namespace:DotNetProjects.Wpf.Toolkit;assembly:DotNetProjects.Wpf.Toolkit"`
and
`"clr-namespace:DotNetProjects.Wpf.Extended.Toolkit;assembly:DotNetProjects.Wpf.Extended.Toolkit"`
and
`"clr-namespace:Xceed.Wpf.Toolkit;assembly:DotNetProjects.Wpf.Toolkit"`

Got errors like "The name "ColorPicker" was not found in the namespace..."

**Comment by SkyFoxCoder** [comment]
Almost there, last one was good, only missing the 'Extended':

`clr-namespace:Xceed.Wpf.Toolkit;assembly:DotNetProjects.Wpf.Extended.Toolkit"`

**Comment by MichaelTietz** [comment]
Thank you SkyFoxCoder!

**Comment by jogibear9988** [comment]
Try Resharper, it helps with xaml imports
