### ISSUE TITLE
Visual Studio 2022 can't add controls to toolbox

### ISSUE THREAD

**Issue by charesch** [dotnetprojects/WpfExtendedToolkit#32]
I am using VS 2022 to create a simple .net 6.0 application. I need the maskedtextbox but i can't add the controls to my toolbox. 

I installed the package via nuget package manager. In the toolbox, I've tried adding a tab, then chose items and add the DotNetProjects.Wpf.Extended.Toolkit.dll but it throws this error : 

"*.dll targets a platform whose toolbox items cannot be enumerated dynamically"

What am i doing wrong?
Thank you very much for your time

**Comment by jogibear9988** [comment]
Think it's an issue with the designer:

https://github.com/MahApps/MahApps.Metro/issues/3734

**Comment by jogibear9988** [comment]
You can use the items, but not via the toolbox

**Comment by jogibear9988** [comment]
i've now also created a net6 version, maybe this helps

**Comment by charesch** [comment]
You're right, it works when you add the controls directly in xaml. It displays at design time and does its job at run time. 
I would like to see the list in my toolbox, but it is a minor issue. I've got what i wanted.

Thank you for your help!
