### ISSUE TITLE
LayoutItemTemplateSelector item error

### ISSUE THREAD

**Issue by mguerrini** [dotnetprojects/WpfExtendedToolkit#8]
I have implemented DataTemplateSelector for LayoutItemTemplateSelector and override the method **DataTemplate SelectTemplate(object item, DependencyObject container).** 

I insert a new document taht is an instance of **ViewModel**, and when the method of the **LayoutItemTemplateSelector** is invoked the **item** parameter is an instance of ContentPresenter, and the content of this object is the ViewModel that i was created. The **container** parameter is other instance of ContentPresenter. I test the AvalonDock V2.0 and work fine, the item parameter is the instance of ViewModel and container is a ContentPresenter. 

Thanks.

**Comment by jogibear9988** [comment]
And now? Do you have a problem?

**Comment by jogibear9988** [comment]
closed cause no question
