### ISSUE TITLE
When I select theme in AvalonDock DockingManager, application crashed when it starts

### ISSUE THREAD

**Issue by jarkor** [dotnetprojects/WpfExtendedToolkit#9]
When I select any theme (by xaml declaration <xcad:DockingManager.Theme> or in application code) for dockingManager (AvalonDock) and run application, application crashed with that message like this:
FileNotFoundException: Unable to load file or assembly Xceed.Wpf.AvalonDock.Themes.Aero.
I think that problem is in class AeroTheme (and others) in method GetResourceUri, when composing URI should by used /DotNetProjects.Wpf.AvalonDock.Themes.Aero instead of /Xceed.Wpf.AvalonDock.Themes.Aero.

**Comment by jogibear9988** [comment]
should be fixed
